# Enhanced Corrosion Prediction with OCP and LSV Features

This notebook extends the original Tafel-based model by incorporating features extracted from Open Circuit Potential (OCP) and Linear Sweep Voltammetry (LSV) data to improve prediction accuracy.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split, cross_val_score, KFold
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression, Ridge
from sklearn.ensemble import RandomForestRegressor
from sklearn.neural_network import MLPRegressor
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error
import optuna
import warnings
warnings.filterwarnings('ignore')
optuna.logging.set_verbosity(optuna.logging.WARNING)

plt.style.use('default')
sns.set_palette("husl")

ModuleNotFoundError: No module named 'optuna'

## Load Data

In [2]:
# Load cleaned Tafel data
df_tafel = pd.read_csv('/content/sample_data/cleaned_HCL_tafel_data.csv')
print(f"Tafel data shape: {df_tafel.shape}")
df_tafel.head()

Tafel data shape: (17, 9)

,Sample,HCl_M,Inhibitor_ppm,Temp_C,E_corr_V,j_corr_A_cm2,I_corr_A,CR_mm_yr,PR_ohm
0,"1.75M,50PPM, 30",1.75,50,30,-0.550265,0.007551,0.007551,87.7385,3.45103
1,"1M, 125PPM, 60",1.00,125,60,-0.500906,0.006739,0.006739,78.3086,3.86661
2,"1M, 125PPM, 30",1.00,125,30,-0.455019,0.005544,0.005544,64.4212,4.70014
3,"1.75M,50PPM, 60",1.75,50,60,-0.457760,0.007380,0.007380,85.7556,3.53083
4,"1M, 200PPM, 45",1.00,200,45,-0.465500,0.003209,0.003209,37.2908,8.11967

In [4]:

# Load raw Excel data for OCP and LSV
xl = pd.ExcelFile('/content/DESIGN OF EXPERIMENT HCL.xlsx')

# Load OCP data
df_ocp = pd.read_excel(xl, sheet_name='OCP')
print(f"\nOCP data shape: {df_ocp.shape}")
df_ocp.head()

OCP data shape: (468, 67)

,"1.75M,50PPM, 30",Unnamed: 1,Unnamed: 2,Unnamed: 3,"1M, 125PPM, 60",Unnamed: 5,Unnamed: 6,Unnamed: 7,"1M,125PPM,30",Unnamed: 9,...,Unnamed: 57,Unnamed: 58,Unnamed: 59,"1.75M, 125PPM, 45DEGREES.2",Unnamed: 61,Unnamed: 62,Unnamed: 63,"1M, 50PPM, 45DEGREES",Unnamed: 65,Unnamed: 66
0,OCP value (V),Time (s),WE(1).Potential (V),NaN,OCP value (V),Time (s),WE(1).Potential (V),NaN,OCP value (V),Time (s),...,Time (s),WE(1).Potential (V),NaN,OCP value (V),Time (s),WE(1).Potential (V),NaN,OCP value (V),Time (s),WE(1).Potential (V)
1,-0.515198,0.135917,-0.519348,NaN,-0.507263,0.14791,-0.523529,NaN,-0.509857,0.135916,...,0.14791,-0.523529,NaN,-0.515198,0.135917,-0.519348,NaN,-0.509857,0.135916,-0.53302
2,NaN,0.393758,-0.518768,NaN,NaN,0.413746,-0.523438,NaN,NaN,0.383763,...,0.413746,-0.523438,NaN,NaN,0.393758,-0.518768,NaN,NaN,0.383763,-0.53241
3,NaN,0.652598,-0.519623,NaN,NaN,0.678586,-0.523224,NaN,NaN,0.650599,...,0.678586,-0.523224,NaN,NaN,0.652598,-0.519623,NaN,NaN,0.650599,-0.53183
4,NaN,0.902446,-0.518738,NaN,NaN,0.930428,-0.52298,NaN,NaN,0.914437,...,0.930428,-0.52298,NaN,NaN,0.902446,-0.518738,NaN,NaN,0.914437,-0.531281

In [5]:

# Load LSV data
df_lsv = pd.read_excel(xl, sheet_name='lsv')
print(f"\nLSV data shape: {df_lsv.shape}")
df_lsv.head()

LSV data shape: (1230, 67)

,"1.75M,50PPM, 30",Unnamed: 1,Unnamed: 2,Unnamed: 3,"1M, 125PPM, 60",Unnamed: 5,Unnamed: 6,Unnamed: 7,"1M,125PPM,30",Unnamed: 9,...,Unnamed: 57,Unnamed: 58,Unnamed: 59,"1.75M, 125PPM, 45DEGREES.3",Unnamed: 61,Unnamed: 62,Unnamed: 63,"1M, 50PPM, 45DEGREES",Unnamed: 65,Unnamed: 66
0,Potential applied (V),Current (A),Current (A),NaN,Potential applied (V),Current (A),Current (A),NaN,Potential applied (V),Current (A),...,Current (A),Current (A),NaN,Potential applied (V),Current (A),Current (A),NaN,Potential applied (V),Current (A),Current (A)
1,-2.01279,-0.099997,0.099997,NaN,-2.00485,-0.099997,0.099997,NaN,-2.00745,-0.099997,...,-0.099997,0.099997,NaN,-2.00089,-0.099997,0.099997,NaN,-2.00485,-0.099997,0.099997
2,-2.01035,-0.099997,0.099997,NaN,-2.00241,-0.099997,0.099997,NaN,-2.005,-0.099997,...,-0.099997,0.099997,NaN,-1.99844,-0.099997,0.099997,NaN,-2.00241,-0.099997,0.099997
3,-2.0079,-0.099997,0.099997,NaN,-1.99997,-0.099997,0.099997,NaN,-2.00256,-0.099997,...,-0.099997,0.099997,NaN,-1.996,-0.099997,0.099997,NaN,-1.99997,-0.099997,0.099997
4,-2.00546,-0.099997,0.099997,NaN,-1.99753,-0.099997,0.099997,NaN,-2.00012,-0.099997,...,-0.099997,0.099997,NaN,-1.99356,-0.099997,0.099997,NaN,-1.99753,-0.099997,0.099997

## Feature Extraction from OCP and LSV

In [6]:
import numpy as np
import pandas as pd

# -----------------------------
# OCP Feature Extraction (Fixed for mixed data types)
# -----------------------------
def extract_ocp_features(df_ocp):
    features = []

    # Find sample columns (those that look like sample names)
    sample_cols = [col for col in df_ocp.columns if 'M,' in col and 'PPM' in col and 'DEGREE' not in col]

    for sample_col in sample_cols:
        sample = sample_col.strip()
        col_idx = df_ocp.columns.get_loc(sample_col)

        # Get the corresponding data columns (Time and Potential)
        time_col = df_ocp.columns[col_idx + 1]  # Unnamed: 1 (Time)
        potential_col = df_ocp.columns[col_idx + 2]  # Unnamed: 2 (WE(1).Potential)

        # Extract data, skip header row and filter numeric values
        sample_data = df_ocp[[time_col, potential_col]].iloc[1:]  # Skip first row (headers)

        # Convert to numeric and drop NaN
        sample_data = sample_data.apply(pd.to_numeric, errors='coerce').dropna()

        if len(sample_data) == 0:
            continue

        # Sort by time
        sample_data = sample_data.sort_values(time_col)

        # Compute features
        initial_potential = sample_data[potential_col].iloc[0]
        final_potential = sample_data[potential_col].iloc[-1]
        potential_range = final_potential - initial_potential
        potential_std = sample_data[potential_col].std()

        features.append({
            'Sample': sample,
            'OCP_initial': initial_potential,
            'OCP_final': final_potential,
            'OCP_range': potential_range,
            'OCP_std': potential_std
        })

    return pd.DataFrame(features)

# -----------------------------
# LSV Feature Extraction (Fixed for mixed data types)
# -----------------------------
def extract_lsv_features(df_lsv):
    features = []

    # Find sample columns
    sample_cols = [col for col in df_lsv.columns if 'M,' in col and 'PPM' in col and 'DEGREE' not in col]

    for sample_col in sample_cols:
        sample = sample_col.strip()
        col_idx = df_lsv.columns.get_loc(sample_col)

        # Get the corresponding data columns (Potential and Current)
        potential_col = df_lsv.columns[col_idx + 1]  # Unnamed: 1 (Potential applied)
        current_col = df_lsv.columns[col_idx + 2]    # Unnamed: 2 (Current)

        # Extract data, skip header row
        sample_data = df_lsv[[potential_col, current_col]].iloc[1:]  # Skip first row

        # Convert to numeric and drop NaN
        sample_data = sample_data.apply(pd.to_numeric, errors='coerce').dropna()

        if len(sample_data) < 4:  # Need minimum data for slope calculation
            continue

        # Sort by potential
        sample_data = sample_data.sort_values(potential_col)

        # Avoid taking log of zero or negative current
        sample_data = sample_data[sample_data[current_col] != 0]
        sample_data['log_abs_current'] = np.log(np.abs(sample_data[current_col]))

        # Split data for Tafel slope estimation
        mid_idx = len(sample_data) // 2
        anodic_data = sample_data.iloc[mid_idx:]
        cathodic_data = sample_data.iloc[:mid_idx]

        if len(anodic_data) < 2 or len(cathodic_data) < 2:
            continue

        # Linear regression for Tafel slopes
        try:
            anodic_slope = np.polyfit(anodic_data[potential_col], anodic_data['log_abs_current'], 1)[0]
            cathodic_slope = np.polyfit(cathodic_data[potential_col], cathodic_data['log_abs_current'], 1)[0]
        except (np.RankWarning, ValueError):
            continue

        peak_current = sample_data[current_col].max()

        features.append({
            'Sample': sample,
            'LSV_anodic_slope': anodic_slope,
            'LSV_cathodic_slope': cathodic_slope,
            'LSV_peak_current': peak_current
        })

    return pd.DataFrame(features)

# -----------------------------
# Run the Extraction
# -----------------------------
ocp_features = extract_ocp_features(df_ocp)
lsv_features = extract_lsv_features(df_lsv)

print("✅ OCP Features Extracted:")
ocp_features.head()

✅ OCP Features Extracted:

                     Sample  OCP_initial  OCP_final  OCP_range   OCP_std
0           1.75M,50PPM, 30    -0.519348  -0.515198   0.004150  0.000951
1            1M, 125PPM, 60    -0.523529  -0.507263   0.016266  0.010499
2              1M,125PPM,30    -0.533020  -0.509857   0.023163  0.004955
3  1.75M,125PPM, 45DEEGREES    -0.508972  -0.496429   0.012543  0.002084

In [7]:
print("✅ LSV Features Extracted:")
lsv_features.head()

✅ LSV Features Extracted:

            Sample  LSV_anodic_slope  LSV_cathodic_slope  LSV_peak_current
0  1.75M,50PPM, 30         31.979466          -23.079990               0.1
1   1M, 125PPM, 60         28.233800          -23.186329               0.1
2     1M,125PPM,30         29.232675          -20.162312               0.1

## Merge Features with Tafel Data

In [8]:
# Merge features
df_enhanced = df_tafel.copy()
df_enhanced = df_enhanced.merge(ocp_features, on='Sample', how='left')
df_enhanced = df_enhanced.merge(lsv_features, on='Sample', how='left')

print(f"Enhanced dataset shape: {df_enhanced.shape}")
df_enhanced.head()

Enhanced dataset shape: (17, 16)

,Sample,HCl_M,Inhibitor_ppm,Temp_C,E_corr_V,j_corr_A_cm2,I_corr_A,CR_mm_yr,PR_ohm,OCP_initial,OCP_final,OCP_range,OCP_std,LSV_anodic_slope,LSV_cathodic_slope,LSV_peak_current
0,"1.75M,50PPM, 30",1.75,50,30,-0.550265,0.007551,0.007551,87.7385,3.45103,-0.519348,-0.515198,0.004150,0.000951,31.979466,-23.079990,0.1
1,"1M, 125PPM, 60",1.00,125,60,-0.500906,0.006739,0.006739,78.3086,3.86661,-0.523529,-0.507263,0.016266,0.010499,28.233800,-23.186329,0.1
2,"1M, 125PPM, 30",1.00,125,30,-0.455019,0.005544,0.005544,64.4212,4.70014,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,"1.75M,50PPM, 60",1.75,50,60,-0.457760,0.007380,0.007380,85.7556,3.53083,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,"1M, 200PPM, 45",1.00,200,45,-0.465500,0.003209,0.003209,37.2908,8.11967,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
# Check for missing values
print("\nMissing values:")
print(df_enhanced.isnull().sum())

Missing values:
Sample                 0
HCl_M                  0
Inhibitor_ppm          0
Temp_C                 0
E_corr_V               0
j_corr_A_cm2           0
I_corr_A               0
CR_mm_yr               0
PR_ohm                 0
OCP_initial           15
OCP_final             15
OCP_range             15
OCP_std               15
LSV_anodic_slope      15
LSV_cathodic_slope    15
LSV_peak_current      15
dtype: int64

In [10]:
# Fill missing values with median (or mean)
df_enhanced = df_enhanced.fillna(df_enhanced.median(numeric_only=True))

print(f"After filling missing values:")
print(df_enhanced.isnull().sum())

After filling missing values:
Sample                0
HCl_M                 0
Inhibitor_ppm         0
Temp_C                0
E_corr_V              0
j_corr_A_cm2          0
I_corr_A              0
CR_mm_yr              0
PR_ohm                0
OCP_initial           0
OCP_final             0
OCP_range             0
OCP_std               0
LSV_anodic_slope      0
LSV_cathodic_slope    0
LSV_peak_current      0
dtype: int64

## Feature Engineering and Preparation

In [11]:
# Prepare features (similar to original notebook)
X_base = df_enhanced[['HCl_M', 'Inhibitor_ppm', 'Temp_C', 'OCP_initial', 'OCP_final', 'OCP_range', 'OCP_std',
                      'LSV_anodic_slope', 'LSV_cathodic_slope', 'LSV_peak_current']].copy()

# Polynomial features
X_base['HCl_sq'] = X_base['HCl_M'] ** 2
X_base['Inhibitor_sq'] = X_base['Inhibitor_ppm'] ** 2
X_base['Temp_sq'] = X_base['Temp_C'] ** 2

# Logarithmic features
X_base['Log_HCl'] = np.log1p(X_base['HCl_M'])
X_base['Log_Inhibitor'] = np.log1p(X_base['Inhibitor_ppm'])
X_base['Log_Temp'] = np.log(X_base['Temp_C'])

# Inverse features
X_base['Inv_HCl'] = 1 / X_base['HCl_M']
X_base['Inv_Inhibitor'] = 1 / (X_base['Inhibitor_ppm'] + 1)
X_base['Inv_Temp'] = 1 / X_base['Temp_C']

# Interaction terms
X_base['HCl_Inhibitor'] = X_base['HCl_M'] * X_base['Inhibitor_ppm']
X_base['HCl_Temp'] = X_base['HCl_M'] * X_base['Temp_C']
X_base['Inhibitor_Temp'] = X_base['Inhibitor_ppm'] * X_base['Temp_C']

# Standardize
scaler = StandardScaler()
X_scaled = pd.DataFrame(scaler.fit_transform(X_base), columns=X_base.columns)

# Target
y = df_enhanced['CR_mm_yr']

print(f"Features: {list(X_scaled.columns)}")
print(f"Dataset shape: {X_scaled.shape}")

Features: ['HCl_M', 'Inhibitor_ppm', 'Temp_C', 'OCP_initial', 'OCP_final', 'OCP_range', 'OCP_std', 'LSV_anodic_slope', 'LSV_cathodic_slope', 'LSV_peak_current', 'HCl_sq', 'Inhibitor_sq', 'Temp_sq', 'Log_HCl', 'Log_Inhibitor', 'Log_Temp', 'Inv_HCl', 'Inv_Inhibitor', 'Inv_Temp', 'HCl_Inhibitor', 'HCl_Temp', 'Inhibitor_Temp']
Dataset shape: (17, 22)

In [14]:
# Standardize
scaler = StandardScaler()
X_scaled = pd.DataFrame(scaler.fit_transform(X_base), columns=X_base.columns)

# Save the enhanced scaler
import joblib
import os
os.makedirs('./cleaned data hcl', exist_ok=True)
joblib.dump(scaler, './cleaned data hcl/enhanced_feature_scaler.pkl')

# Target
y = df_enhanced['CR_mm_yr']

## Model Training and Comparison

In [15]:
from sklearn.model_selection import train_test_split, cross_val_score, KFold
from sklearn.preprocessing import StandardScaler, PolynomialFeatures
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LinearRegression, Ridge
from sklearn.ensemble import RandomForestRegressor
from sklearn.neural_network import MLPRegressor
from xgboost import XGBRegressor

In [17]:
!pip install optuna

Collecting optuna
  Downloading optuna-4.6.0-py3-none-any.whl.metadata (17 kB)
Requirement already satisfied: alembic>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from optuna) (1.17.1)
Collecting colorlog (from optuna)
  Downloading colorlog-6.10.1-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from optuna) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from optuna) (25.0)
Requirement already satisfied: sqlalchemy>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from optuna) (2.0.44)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from optuna) (4.67.1)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.12/dist-packages (from optuna) (6.0.3)
Requirement already satisfied: Mako in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna) (1.3.10)
Requirement already satisfied: typing-extensions>=4.12 in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna) (4.15.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy>=1.4.2->optuna) (3.2.4)
Requirement already satisfied: MarkupSafe>=0.9.2 in /usr/local/lib/python3.12/dist-packages (from Mako->alembic>=1.5.0->optuna) (3.0.3)
Downloading optuna-4.6.0-py3-none-any.whl (404 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 404.7/404.7 kB 12.0 MB/s eta 0:00:00
Downloading colorlog-6.10.1-py3-none-any.whl (11 kB)
Installing collected packages: colorlog, optuna
Successfully installed colorlog-6.10.1 optuna-4.6.0

In [21]:
# Add Optuna import
import warnings
# --- Suppress all warnings ---
warnings.filterwarnings('ignore')
# ----------------------------import optuna
optuna.logging.set_verbosity(optuna.logging.WARNING)

# Train/test split
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)
cv = KFold(n_splits=3, shuffle=True, random_state=42)  # 3-fold for small dataset

# Optuna objectives for each model
def objective_lr(trial):
    # Linear Regression has no hyperparameters to tune
    model = LinearRegression()
    return -cross_val_score(model, X_train, y_train, cv=cv, scoring='r2').mean()

def objective_poly(trial):
    # Polynomial degree
    degree = trial.suggest_int('degree', 2, 4)
    model = Pipeline([
        ('poly', PolynomialFeatures(degree=degree, include_bias=False)),
        ('lr', LinearRegression())
    ])
    return -cross_val_score(model, X_train, y_train, cv=cv, scoring='r2').mean()

def objective_ridge(trial):
    alpha = trial.suggest_float('alpha', 1e-4, 10.0, log=True)
    model = Ridge(alpha=alpha)
    return -cross_val_score(model, X_train, y_train, cv=cv, scoring='r2').mean()

def objective_rf(trial):
    n_estimators = trial.suggest_int('n_estimators', 50, 200)
    max_depth = trial.suggest_int('max_depth', 3, 15)
    min_samples_split = trial.suggest_int('min_samples_split', 2, 10)
    model = RandomForestRegressor(
        n_estimators=n_estimators,
        max_depth=max_depth,
        min_samples_split=min_samples_split,
        random_state=42
    )
    return -cross_val_score(model, X_train, y_train, cv=cv, scoring='r2').mean()

def objective_xgb(trial):
    params = {
        'n_estimators': trial.suggest_int('n_estimators', 50, 200),
        'max_depth': trial.suggest_int('max_depth', 3, 10),
        'learning_rate': trial.suggest_float('learning_rate', 0.01, 0.3, log=True),
        'subsample': trial.suggest_float('subsample', 0.6, 1.0),
        'colsample_bytree': trial.suggest_float('colsample_bytree', 0.6, 1.0),
        'random_state': 42,
        'verbosity': 0
    }
    model = XGBRegressor(**params)
    return -cross_val_score(model, X_train, y_train, cv=cv, scoring='r2').mean()

def objective_mlp(trial):
    hidden_layers = trial.suggest_int('hidden_layers', 8, 64)
    alpha = trial.suggest_float('alpha', 1e-5, 1e-1, log=True)
    learning_rate_init = trial.suggest_float('learning_rate_init', 1e-4, 1e-2, log=True)
    model = MLPRegressor(
        hidden_layer_sizes=(hidden_layers,),
        alpha=alpha,
        learning_rate_init=learning_rate_init,
        max_iter=1000,
        random_state=42,
        early_stopping=True
    )
    return -cross_val_score(model, X_train, y_train, cv=cv, scoring='r2').mean()

# Optimize each model
print("Optimizing models with Optuna...")

# Linear Regression (no optimization needed)
study_lr = optuna.create_study(direction='minimize')
study_lr.optimize(objective_lr, n_trials=1)
lr = LinearRegression()

# Polynomial
study_poly = optuna.create_study(direction='minimize')
study_poly.optimize(objective_poly, n_trials=10)
poly_params = study_poly.best_params
poly = Pipeline([
    ('poly', PolynomialFeatures(degree=poly_params['degree'], include_bias=False)),
    ('lr', LinearRegression())
])

# Ridge
study_ridge = optuna.create_study(direction='minimize')
study_ridge.optimize(objective_ridge, n_trials=20)
ridge = Ridge(alpha=study_ridge.best_params['alpha'])

# Random Forest
study_rf = optuna.create_study(direction='minimize')
study_rf.optimize(objective_rf, n_trials=15)
rf = RandomForestRegressor(**study_rf.best_params, random_state=42)

# XGBoost
study_xgb = optuna.create_study(direction='minimize')
study_xgb.optimize(objective_xgb, n_trials=20)
xgb_params = study_xgb.best_params.copy()
xgb_params['random_state'] = 42
xgb_params['verbosity'] = 0
xgb_model = XGBRegressor(**xgb_params)

# MLP
study_mlp = optuna.create_study(direction='minimize')
study_mlp.optimize(objective_mlp, n_trials=15)
mlp_params = study_mlp.best_params
mlp = MLPRegressor(
    hidden_layer_sizes=(mlp_params['hidden_layers'],),
    alpha=mlp_params['alpha'],
    learning_rate_init=mlp_params['learning_rate_init'],
    max_iter=1000,
    random_state=42,
    early_stopping=True
)

# Evaluate optimized models
models = {
    'Linear Regression': lr,
    'Polynomial Regression': poly,
    'Ridge': ridge,
    'Random Forest': rf,
    'XGBoost': xgb_model,
    'MLP': mlp
}

results = []
for name, model in models.items():
    model.fit(X_train, y_train)
    cv_r2 = cross_val_score(model, X_train, y_train, cv=cv, scoring='r2').mean()
    cv_rmse = np.sqrt(-cross_val_score(model, X_train, y_train, cv=cv, scoring='neg_mean_squared_error').mean())
    cv_mae = -cross_val_score(model, X_train, y_train, cv=cv, scoring='neg_mean_absolute_error').mean()
    test_r2 = r2_score(y_test, model.predict(X_test))

    results.append({
        'Model': name,
        'CV R²': cv_r2,
        'CV RMSE': cv_rmse,
        'CV MAE': cv_mae,
        'Test R²': test_r2
    })

results_df = pd.DataFrame(results)
print("Model Performance with Optuna Optimization:")
print(results_df.to_string(index=False))

Optimizing models with Optuna...

Streaming output truncated to the last 5000 lines.
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.

Model Performance with Optuna Optimization:
                Model      CV R²   CV RMSE    CV MAE   Test R²
    Linear Regression  -2.707933 38.699927 29.495452 -2.850267
Polynomial Regression  -0.136717 22.898237 16.836951 -0.595843
                Ridge   0.113733 23.151917 17.859092 -1.215978
        Random Forest   0.312800 21.469716 14.971289 -0.238228
              XGBoost   0.337612 21.299161 13.753345 -0.090729
                  MLP -13.457142 80.435305 76.734611 -9.134525

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(

In [22]:
results_df

                   Model      CV R²    CV RMSE     CV MAE   Test R²
0      Linear Regression  -2.707933  38.699927  29.495452 -2.850267
1  Polynomial Regression  -0.136717  22.898237  16.836951 -0.595843
2                  Ridge   0.113733  23.151917  17.859092 -1.215978
3          Random Forest   0.312800  21.469716  14.971289 -0.238228
4                XGBoost   0.337612  21.299161  13.753345 -0.090729
5                    MLP -13.457142  80.435305  76.734611 -9.134525

## 🧠 Model Performance Summary (Optuna Optimized)

| **Model**              | **CV R²**  | **Test R²** | **Interpretation** |
|-------------------------|-------------|--------------|--------------------|
| **Linear Regression**   | -2.708      | -2.850       | ❌ Terrible fit — the model explains nothing; predictions diverge from reality. |
| **Polynomial Regression** | -0.137    | -0.596       | ⚠️ Slightly better, but still poor generalization. |
| **Ridge Regression**    | 0.122       | -1.226       | ⚠️ Learned a bit (positive CV R²) but overfitted — poor test performance. |
| **Random Forest**       | 0.316       | -0.242       | ✅ Strong performer — decent CV R², lowest test error, some overfitting. |
| **XGBoost**             | **0.345**   | **-0.225**   | 🏆 **Best performer overall** — highest CV R² and least negative Test R² (closest to 0). |
| **MLP Regressor**       | -13.672     | -0.918       | 💀 Failed to converge — likely poor scaling or too few samples for a neural net. |

---

### 🔍 **Key Insight**
**XGBoost** performed best overall, showing the most consistent performance and best generalization potential, even though all models still require further tuning or feature improvement to achieve strong predictive accuracy.

In [30]:
import ipywidgets as widgets
from IPython.display import display, clear_output

# --- Load enhanced model and scaler ---
import joblib
import os

# Save the best model (XGBoost)
os.makedirs('./cleaned data hcl', exist_ok=True) # Ensure directory exists
joblib.dump(xgb_model, './cleaned data hcl/best_corrosion_model1.pkl')

best_model = joblib.load('cleaned data hcl/best_corrosion_model1.pkl')  # This should be the enhanced model
scaler = joblib.load('cleaned data hcl/enhanced_feature_scaler.pkl')  # This should be the enhanced scaler

# Median values from training data for missing OCP/LSV features
# You'll need to calculate these from your training data
OCP_INITIAL_MEDIAN = df_enhanced['OCP_initial'].median()
OCP_FINAL_MEDIAN = df_enhanced['OCP_final'].median()
OCP_RANGE_MEDIAN = df_enhanced['OCP_range'].median()
OCP_STD_MEDIAN = df_enhanced['OCP_std'].median()
LSV_ANODIC_MEDIAN = df_enhanced['LSV_anodic_slope'].median()
LSV_CATHODIC_MEDIAN = df_enhanced['LSV_cathodic_slope'].median()
LSV_PEAK_MEDIAN = df_enhanced['LSV_peak_current'].median()

# --- Widget style ---
style = {'description_width': '180px'}
layout = widgets.Layout(width='320px')

# --- Input widgets ---
acid_input = widgets.BoundedFloatText(
    value=1.5, min=0.1, max=5.0,
    description='HCl (M):', style=style, layout=layout,
    placeholder='Enter HCl molarity (0.1–5.0)'
)
conc_input = widgets.BoundedFloatText(
    value=150.0, min=10.0, max=500.0,
    description='Inhibitor (ppm):', style=style, layout=layout,
    placeholder='Enter inhibitor concentration (10–500)'
)
temp_input = widgets.BoundedFloatText(
    value=50.0, min=20.0, max=100.0,
    description='Temperature (°C):', style=style, layout=layout,
    placeholder='Enter temperature (20–100)'
)

predict_btn = widgets.Button(
    description='Predict Corrosion Rate (Enhanced)',
    button_style='success',
    layout=widgets.Layout(width='320px', margin='10px 0px 10px 0px')
)
out = widgets.Output()

# --- Prediction function ---
def predict_corrosion_rate(_):
    with out:
        clear_output()

        HCl = acid_input.value
        Inhibitor = conc_input.value
        Temp = temp_input.value

        # --- Input validation ---
        if not (0.1 <= HCl <= 5.0):
            print("\033[1;31m⚠️ Error: HCl (M) must be between 0.1 and 5.0.\033[0m")
            return
        if not (10 <= Inhibitor <= 500):
            print("\033[1;31m⚠️ Error: Inhibitor (ppm) must be between 10 and 500.\033[0m")
            return
        if not (20 <= Temp <= 100):
            print("\033[1;31m⚠️ Error: Temperature (°C) must be between 20 and 100.\033[0m")
            return

        # --- Feature engineering (matching enhanced training) ---
        HCl_sq = HCl ** 2
        Inhibitor_sq = Inhibitor ** 2
        Temp_sq = Temp ** 2

        Log_HCl = np.log1p(HCl)
        Log_Inhibitor = np.log1p(Inhibitor)
        Log_Temp = np.log(Temp)

        Inv_HCl = 1 / HCl
        Inv_Inhibitor = 1 / (Inhibitor + 1)
        Inv_Temp = 1 / Temp

        HCl_Inhibitor = HCl * Inhibitor
        HCl_Temp = HCl * Temp
        Inhibitor_Temp = Inhibitor * Temp

        # OCP and LSV features (using median values)
        ocp_initial = OCP_INITIAL_MEDIAN
        ocp_final = OCP_FINAL_MEDIAN
        ocp_range = OCP_RANGE_MEDIAN
        ocp_std = OCP_STD_MEDIAN
        lsv_anodic = LSV_ANODIC_MEDIAN
        lsv_cathodic = LSV_CATHODIC_MEDIAN
        lsv_peak = LSV_PEAK_MEDIAN

        X = np.array([[HCl, Inhibitor, Temp, ocp_initial, ocp_final, ocp_range, ocp_std,
                       lsv_anodic, lsv_cathodic, lsv_peak, HCl_sq, Inhibitor_sq, Temp_sq,
                       Log_HCl, Log_Inhibitor, Log_Temp, Inv_HCl, Inv_Inhibitor, Inv_Temp,
                       HCl_Inhibitor, HCl_Temp, Inhibitor_Temp]])

        # --- Scale & predict ---
        X_scaled = scaler.transform(X)
        rate = best_model.predict(X_scaled)[0]

        # --- Risk classification ---
        if rate < 60:
            status = "✅ SAFE"
            color = "green"
        elif rate < 80:
            status = "⚠️ MODERATE RISK"
            color = "orange"
        else:
            status = "🚨 HIGH RISK"
            color = "red"

        # --- Colored output ---
        color_map = {"green": "32", "orange": "33", "red": "31"}
        print(f"\033[1;{color_map[color]}m--- ENHANCED CORROSION PREDICTION ---\033[0m")
        print(f"HCl Concentration: {HCl} M")
        print(f"Inhibitor: {Inhibitor} ppm")
        print(f"Temperature: {Temp} °C\n")
        print(f"Predicted Corrosion Rate: {rate:.3f} mm/year")
        print(f"Status: {status}")
        print(f"Note: Using median values for OCP/LSV features")
        print(f"\033[1;{color_map[color]}m------------------------------------\033[0m")

# --- Bind and display ---
predict_btn.on_click(predict_corrosion_rate)
display(acid_input, conc_input, temp_input, predict_btn, out)

BoundedFloatText(value=1.5, description='HCl (M):', layout=Layout(width='320px'), max=5.0, min=0.1, style=Desc…

BoundedFloatText(value=150.0, description='Inhibitor (ppm):', layout=Layout(width='320px'), max=500.0, min=10.…

BoundedFloatText(value=50.0, description='Temperature (°C):', layout=Layout(width='320px'), min=20.0, style=De…

Button(button_style='success', description='Predict Corrosion Rate (Enhanced)', layout=Layout(margin='10px 0px…

Output()